language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer config -g github-oauth.github.com $GITHUB_AUTH_TOKEN
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer exec codecept build -v
  - composer exec codecept run -v
